FROM python:3.13-alpine

RUN apk add --no-cache gcc musl-dev libpq-dev

WORKDIR /tests
COPY tests/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY tests/ .

CMD ["pytest", "-v", "--tb=short"]
