[databases]
* = host=db port=5432

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432
; Uncomment the line below if you are putting NGINX in front of PgBouncer
; and have 'proxy_protocol on;' in your NGINX stream config. This allows
; PgBouncer to receive the true client IP from NGINX for pg_hba.conf locking.
; listen_options = proxy_protocol
auth_type = hba
auth_user = pgbouncer_auth
auth_query = SELECT * FROM pgbouncer_get_user($1)
auth_dbname = pgmanager
auth_hba_file = /etc/pgbouncer/shared/pg_hba.conf
admin_users = pgbouncer_auth
pool_mode = transaction
default_pool_size = 20
max_client_conn = 100
server_reset_query = DISCARD ALL
log_connections = 1
log_disconnections = 1
